const $=s=>document.querySelector(s);
const BASE_PAIRS=[
['oi','oi'],['olá','olá'],['bom dia','bom dia'],['boa tarde','boa tarde'],['boa noite','boa noite'],['e aí','oi como você está'],['oi tudo bem','oi tudo bem sim'],
['como você está','estou bem'],['como você está hoje','estou bem e aprendendo'],['tudo bem com você','sim estou bem'],['você está bem','sim estou bem'],
['quem é você','eu sou uma mosca neural'],['o que você é','eu sou uma rede neural aprendendo a conversar'],['qual é seu nome','pode me chamar de fly'],['você é uma mosca','sim eu sou uma mosca neural'],
['você pensa','eu processo sinais e aprendo com exemplos'],['você aprende','sim eu aprendo com treino e correções'],['você está aprendendo','sim estou aprendendo agora'],
['o que você quer','eu quero aprender e conversar'],['você quer comida','sim eu quero comida'],['está com fome','sim eu gosto de comida'],['o que moscas comem','eu aprendi a associar comida com recompensa'],
['isso é comida','sim isso é comida'],['comida é boa','sim comida é boa'],['você gosta de comida','sim eu gosto de comida'],['isso é perigoso','se é perigoso eu devo evitar'],['há perigo','eu entendi que existe perigo'],['você sente perigo','eu reconheço sinais de perigo'],
['tem luz','sim existe luz'],['está escuro','sim está escuro'],['você vê luz','eu reconheço o conceito de luz'],['vá para a esquerda','esquerda'],['vá para a direita','direita'],['pare agora','vou parar'],['ande agora','vou andar'],
['isso dói','dor é um sinal ruim'],['dor é ruim','sim dor é ruim'],['isso é bom','sim isso é bom'],['isso é ruim','sim isso é ruim'],['você entende português','estou aprendendo português'],['podemos conversar','sim podemos conversar'],['fale comigo','estou aqui'],['me responda','estou respondendo'],
['o que você sabe','sei algumas palavras e relações que aprendi'],['você sabe tudo','não ainda tenho muito para aprender'],['você é inteligente','estou tentando aprender padrões'],['sim ou não','sim'],['isso não é comida','não isso não é comida'],['pedra é comida','não pedra não é comida'],['parede é comida','não parede não é comida'],
['onde você está','estou aqui no simulador'],['onde está a comida','eu preciso de contexto para saber'],['o que é aqui','aqui é onde estamos conversando'],['obrigado','de nada'],['valeu','de nada'],['tchau','tchau'],['até mais','até mais'],
['qual sua função','aprender padrões e tentar conversar'],['por que você existe','para experimentar aprendizagem neural'],['quem te ensina','você e os exemplos de treino me ensinam'],['você lembra de mim','eu uso o contexto recente da conversa'],['você consegue conversar naturalmente','estou aprendendo a formar respostas cada vez melhores'],
['o que acontece quando eu te corrijo','a correção entra no meu treino'],['o treino está funcionando','minhas métricas mostram se estou melhorando'],['você tem medo','eu não sinto medo como um animal real'],['você sente dor','eu não sinto dor real mas posso aprender o conceito'],['você tem consciência','não eu sou uma rede experimental'],
['qual é seu objetivo','aprender a conversar com você'],['quer aprender mais','sim quero aprender mais'],['vamos treinar','sim vamos treinar'],['boa resposta','obrigado'],['resposta ruim','vou tentar aprender com a correção'],['tente de novo','vou tentar novamente'],
['o que é comida','comida é algo associado a alimentação'],['o que é perigo','perigo é um sinal para evitar algo ruim'],['o que é luz','luz é um estímulo visual'],['o que é dor','dor é um sinal associado a algo ruim'],['você prefere luz ou escuro','ainda estou aprendendo preferências'],['você prefere comida ou perigo','comida parece melhor que perigo'],
['olá mosca','olá humano'],['oi mosca','oi humano'],['como vai mosca','estou aprendendo e conversando'],['você está aí','sim estou aqui'],['está me ouvindo','estou recebendo seu texto'],['entendeu','acho que sim'],['não entendeu','então me ensine a resposta melhor']
];
const VAL_PAIRS=[['oi fly','oi'],['como vai você','estou bem'],['quem é a mosca','eu sou uma mosca neural'],['você consegue aprender','sim eu aprendo com treino e correções'],['quer comer','sim eu quero comida'],['isso parece perigoso','se é perigoso eu devo evitar'],['tem claridade','sim existe luz'],['não tem luz','sim está escuro'],['pedra serve de comida','não pedra não é comida'],['vamos conversar um pouco','sim podemos conversar'],['quem está te ensinando','você e os exemplos de treino me ensinam'],['para que você serve','aprender padrões e tentar conversar'],['até logo','até mais'],['muito obrigado','de nada']];
let userPairs=[];try{userPairs=JSON.parse(localStorage.getItem('flytalk-user-pairs-v4')||'[]')}catch{}
let history=[],lastPrompt='',lastContextPrompt='',lastReply='',lastConfidence=0,lastHidden=[];
let running=localStorage.getItem('flytalk-running-v4')!=='0',worker=null;
function addMsg(kind,text){const el=document.createElement('div');el.className='msg '+kind;const who=document.createElement('div');who.className='who';who.textContent=kind==='user'?'VOCÊ':kind==='fly'?'MOSCA':'SISTEMA';if(kind!=='sys')el.appendChild(who);el.appendChild(document.createTextNode(text));$('#chat').appendChild(el);while($('#chat').children.length>70)$('#chat').firstChild.remove();$('#chat').scrollTop=$('#chat').scrollHeight}
function makeContext(text){const recent=history.slice(-4).map(x=>x.role+': '+x.text).join(' | ');return recent?recent+' | user: '+text:'user: '+text}
function saveUserPairs(){localStorage.setItem('flytalk-user-pairs-v4',JSON.stringify(userPairs.slice(-250)))}
function updateTrainButton(){$('#train').textContent=running?'⏸ Pausar treino':'▶ Retomar treino';$('#train').classList.toggle('running',running);$('#state').textContent=running?'TREINANDO':'PAUSADO';localStorage.setItem('flytalk-running-v4',running?'1':'0')}
function startWorker(){if(worker)worker.terminate();worker=new Worker('trainer-worker.js?v=4');let saved=null;try{saved=JSON.parse(localStorage.getItem('flytalk-model-v4')||'null')}catch{}worker.onmessage=e=>{const m=e.data||{};if(m.type==='ready'){$('#vocab').textContent=m.vocab;$('#pairs').textContent=m.pairs;$('#steps').textContent=(m.steps||0).toLocaleString('pt-BR');updateTrainButton()}else if(m.type==='stats'){$('#steps').textContent=m.steps.toLocaleString('pt-BR');$('#speed').textContent=Math.round(m.speed).toLocaleString('pt-BR');$('#loss').textContent=m.loss.toFixed(3);if(m.val!=null){$('#val').textContent=(m.val*100).toFixed(0)+'%';$('#progress').style.width=Math.min(100,m.val*100)+'%'}$('#vocab').textContent=m.vocab;$('#pairs').textContent=m.pairs;$('#trainInfo').textContent=`${Math.floor(m.steps/10000).toLocaleString('pt-BR')} blocos de 10k · nível ${1+(m.level||0)}/3 · continua automaticamente`;$('#event').textContent=`${Math.round(m.speed)} exemplos/s · loss ${m.loss.toFixed(3)}`}else if(m.type==='snapshot'){try{localStorage.setItem('flytalk-model-v4',JSON.stringify(m.state))}catch{}}else if(m.type==='infer'){lastReply=m.text||'...';lastConfidence=m.confidence||0;lastHidden=m.hidden||[];addMsg('fly',lastReply);history.push({role:'fly',text:lastReply});history=history.slice(-8);$('#confidence').style.width=(lastConfidence*100).toFixed(1)+'%';$('#confText').textContent=(lastConfidence*100).toFixed(1)+'%';$('#event').textContent='resposta gerada palavra por palavra';drawHidden()}else if(m.type==='taught'){$('#vocab').textContent=m.vocab;$('#pairs').textContent=m.pairs;$('#userPairs').textContent=userPairs.length;addMsg('sys','Resposta adicionada ao treino contínuo.')}};worker.postMessage({type:'init',pairs:[...BASE_PAIRS,...userPairs],userCount:userPairs.length,valPairs:VAL_PAIRS,state:saved,running,stage:$('#curriculum').value})}
let inferId=0;function send(){const text=$('#input').value.trim();if(!text||!worker)return;$('#input').value='';lastPrompt=text;addMsg('user',text);const prompt=makeContext(text);lastContextPrompt=prompt;history.push({role:'user',text});history=history.slice(-8);worker.postMessage({type:'infer',id:++inferId,prompt})}
$('#send').onclick=send;$('#input').addEventListener('keydown',e=>{if(e.key==='Enter')send()});
$('#train').onclick=()=>{running=!running;worker?.postMessage({type:'run',running});updateTrainButton()};
$('#curriculum').onchange=()=>{worker?.postMessage({type:'stage',stage:$('#curriculum').value});$('#stageInfo').textContent=$('#curriculum').value==='auto'?'Mistura tarefas e aumenta a complexidade conforme o treino avança.':'Foco alterado; o treino continua sem reiniciar.'};
$('#good').onclick=()=>{if(!lastPrompt||!lastReply)return;worker.postMessage({type:'positive',prompt:lastContextPrompt||lastPrompt,reply:lastReply});addMsg('sys','👍 A resposta foi reforçada e entrou no replay.')};
$('#bad').onclick=()=>{if(!lastPrompt)return;addMsg('sys','👎 Marcada como ruim. Escreva abaixo a resposta ideal para ensinar algo útil.');$('#teacher').focus()};
$('#teach').onclick=()=>{const reply=$('#teacher').value.trim();if(!lastPrompt||!reply)return;$('#teacher').value='';const prompt=lastContextPrompt||lastPrompt;userPairs.push([prompt,reply]);userPairs=userPairs.slice(-250);saveUserPairs();worker.postMessage({type:'teach',prompt,reply})};
$('#save').onclick=()=>worker?.postMessage({type:'snapshot'});
$('#reset').onclick=()=>{if(!confirm('Zerar o cérebro e os exemplos ensinados por você?'))return;localStorage.removeItem('flytalk-model-v4');localStorage.removeItem('flytalk-user-pairs-v4');userPairs=[];history=[];startWorker();$('#userPairs').textContent='0';addMsg('sys','Cérebro reiniciado.')};
$('#userPairs').textContent=userPairs.length;updateTrainButton();startWorker();
const cv=$('#brain'),cx=cv.getContext('2d');function drawHidden(){cx.fillStyle='#080d14';cx.fillRect(0,0,cv.width,cv.height);if(!lastHidden.length){cx.fillStyle='#93a2b8';cx.font='16px system-ui';cx.fillText('aguardando uma resposta…',14,24);return}const n=lastHidden.length,bw=cv.width/n;for(let i=0;i<n;i++){const v=lastHidden[i],h=Math.abs(v)*(cv.height*.78);cx.fillStyle=v>=0?'rgba(117,230,165,.78)':'rgba(255,127,139,.72)';cx.fillRect(i*bw+1,cv.height*.5-(v>0?h:0),Math.max(2,bw-2),h)}cx.strokeStyle='#36445a';cx.beginPath();cx.moveTo(0,cv.height*.5);cx.lineTo(cv.width,cv.height*.5);cx.stroke();cx.fillStyle='#93a2b8';cx.font='14px system-ui';cx.fillText('estado oculto da última resposta',12,20)}drawHidden();
setInterval(()=>worker?.postMessage({type:'snapshot'}),20000);