const $=s=>document.querySelector(s);
const BASE_PAIRS=[
['oi','oi'],['olá','olá'],['ei','oi'],['e aí','oi como você está'],['bom dia','bom dia'],['boa tarde','boa tarde'],['boa noite','boa noite'],['oi tudo bem','oi tudo bem sim'],['tudo bem','sim tudo bem'],
['como você está','estou bem'],['como você está hoje','estou bem e aprendendo'],['tudo bem com você','sim estou bem'],['você está bem','sim estou bem'],['como vai','estou bem e aprendendo'],['como vai você','estou bem'],
['quem é você','eu sou uma mosca neural'],['o que você é','eu sou uma rede neural aprendendo a conversar'],['qual é seu nome','pode me chamar de fly'],['você é uma mosca','sim eu sou uma mosca neural'],['quem é a fly','eu sou a fly uma mosca neural'],
['você pensa','eu processo sinais e aprendo com exemplos'],['você aprende','sim eu aprendo com treino e correções'],['você está aprendendo','sim estou aprendendo agora'],['como você aprende','eu aprendo com exemplos correções e repetição'],['o que é aprender','aprender é ajustar meus padrões com os exemplos'],
['o que você quer','eu quero aprender e conversar'],['você quer comida','sim eu quero comida'],['está com fome','eu conheço o conceito de fome e comida'],['o que moscas comem','moscas podem buscar diferentes fontes de alimento'],['você gosta de comida','sim comida é um conceito positivo no meu treino'],
['isso é comida','sim isso é comida'],['comida é boa','sim comida é boa'],['isso é perigoso','se é perigoso eu devo evitar'],['há perigo','eu entendi que existe perigo'],['você sente perigo','eu reconheço sinais associados a perigo'],
['tem luz','sim existe luz'],['está escuro','sim está escuro'],['você vê luz','eu reconheço o conceito de luz'],['o que é luz','luz é um estímulo visual'],['o que é escuro','escuro é ausência ou pouca luz'],
['vá para a esquerda','esquerda'],['vá para a direita','direita'],['pare agora','vou parar'],['ande agora','vou andar'],['o que é esquerda','esquerda é uma direção'],['o que é direita','direita é uma direção'],
['isso dói','dor é um sinal ruim'],['dor é ruim','sim dor é ruim'],['isso é bom','sim isso é bom'],['isso é ruim','sim isso é ruim'],['o que é dor','dor é um conceito associado a algo ruim'],['você sente dor','eu não sinto dor real mas posso aprender o conceito'],
['você entende português','estou aprendendo português'],['podemos conversar','sim podemos conversar'],['fale comigo','estou aqui'],['me responda','estou respondendo'],['responda','estou aqui para responder'],['está me ouvindo','estou recebendo seu texto'],['você está aí','sim estou aqui'],
['o que você sabe','sei algumas palavras e relações que aprendi'],['você sabe tudo','não ainda tenho muito para aprender'],['você é inteligente','estou tentando aprender padrões'],['você consegue aprender sozinha','eu consigo ajustar meus pesos durante o treino'],['você consegue conversar naturalmente','estou aprendendo a formar respostas cada vez melhores'],
['sim ou não','sim'],['isso não é comida','não isso não é comida'],['pedra é comida','não pedra não é comida'],['parede é comida','não parede não é comida'],['fogo é comida','não fogo não é comida'],
['onde você está','estou aqui no simulador'],['onde está a comida','eu preciso de contexto para saber'],['o que é aqui','aqui é onde estamos conversando'],['onde estamos','estamos no laboratório de linguagem'],
['obrigado','de nada'],['muito obrigado','de nada'],['valeu','de nada'],['tchau','tchau'],['até mais','até mais'],['até logo','até mais'],['beleza','beleza'],
['qual sua função','aprender padrões e tentar conversar'],['por que você existe','para experimentar aprendizagem neural'],['quem te ensina','você e os exemplos de treino me ensinam'],['você lembra de mim','eu ainda tenho memória de contexto limitada'],
['o que acontece quando eu te corrijo','a correção entra no meu treino'],['o treino está funcionando','as métricas mostram se eu estou melhorando'],['o que significa loss','loss mede o erro durante o treino'],['o que significa validação','validação testa exemplos separados do treino'],
['você tem medo','eu não sinto medo como um animal real'],['você tem consciência','não eu sou uma rede experimental'],['você sente emoções','eu não sinto emoções reais'],['você é viva','não eu sou uma simulação neural'],
['qual é seu objetivo','aprender a conversar com você'],['quer aprender mais','sim quero aprender mais'],['vamos treinar','sim vamos treinar'],['boa resposta','obrigado'],['resposta ruim','vou tentar aprender com a correção'],['tente de novo','vou tentar novamente'],
['o que é comida','comida é algo associado a alimentação'],['o que é perigo','perigo é um sinal para evitar algo ruim'],['você prefere luz ou escuro','ainda estou aprendendo preferências'],['você prefere comida ou perigo','comida parece melhor que perigo'],
['olá mosca','olá humano'],['oi mosca','oi humano'],['como vai mosca','estou aprendendo e conversando'],['entendeu','acho que sim'],['não entendeu','então me ensine uma resposta melhor'],
['qual é a cor do céu','o céu costuma parecer azul durante o dia'],['quanto é dois mais dois','dois mais dois é quatro'],['qual é o contrário de sim','o contrário de sim é não'],['qual é o contrário de bom','o contrário de bom é ruim'],
['você pode responder frases','sim eu tento gerar respostas palavra por palavra'],['por que você erra','porque minha rede ainda está aprendendo padrões'],['você melhora com treino','sim meus pesos mudam durante o treino'],['quanto mais treino melhor','o treino ajuda mas também preciso de exemplos variados']
];
const VAL_PAIRS=[['oi fly','oi'],['como vai você','estou bem'],['quem é a mosca','eu sou uma mosca neural'],['você consegue aprender','sim eu aprendo com treino e correções'],['quer comer','sim eu quero comida'],['isso parece perigoso','se é perigoso eu devo evitar'],['tem claridade','sim existe luz'],['não tem luz','sim está escuro'],['pedra serve de comida','não pedra não é comida'],['vamos conversar um pouco','sim podemos conversar'],['quem está te ensinando','você e os exemplos de treino me ensinam'],['para que você serve','aprender padrões e tentar conversar'],['até logo','até mais'],['muito obrigado','de nada'],['você sente emoções','eu não sinto emoções reais'],['como você aprende','eu aprendo com exemplos correções e repetição']];
let userPairs=[];try{userPairs=JSON.parse(localStorage.getItem('flytalk-user-pairs-v5')||localStorage.getItem('flytalk-user-pairs-v4')||'[]')}catch{}
let lastPrompt='',lastReply='',lastConfidence=0,lastHidden=[],worker=null,inferId=0,currentSteps=0,running=localStorage.getItem('flytalk-running-v5')!=='0';
const mobile=matchMedia('(max-width:650px)').matches;
function addMsg(kind,text){const el=document.createElement('div');el.className='msg '+kind;const who=document.createElement('div');who.className='who';who.textContent=kind==='user'?'VOCÊ':kind==='fly'?'MOSCA':'SISTEMA';if(kind!=='sys')el.appendChild(who);el.appendChild(document.createTextNode(text));$('#chat').appendChild(el);while($('#chat').children.length>70)$('#chat').firstChild.remove();$('#chat').scrollTop=$('#chat').scrollHeight}
function saveUserPairs(){localStorage.setItem('flytalk-user-pairs-v5',JSON.stringify(userPairs.slice(-300)))}
function pct(v){return Number.isFinite(v)?(v*100).toFixed(v>=.995?0:1)+'%':'—'}
function num(v){return Number(v||0).toLocaleString('pt-BR')}
function setMetric(id,v){const el=$(id);if(el)el.textContent=v}
function updateTrainButton(){setMetric('#train',running?'⏸ Pausar treino':'▶ Retomar treino');$('#train').classList.toggle('running',running);setMetric('#state',running?'TREINANDO MÁXIMO':'PAUSADO');localStorage.setItem('flytalk-running-v5',running?'1':'0')}
function powerMs(){const p=$('#power')?.value||'max';return p==='max'?(mobile?260:440):p==='high'?(mobile?160:260):90}
function startWorker(){if(worker)worker.terminate();worker=new Worker('trainer-worker-v5.js?v=5');let saved=null;try{saved=JSON.parse(localStorage.getItem('flytalk-model-v5')||'null')}catch{}
 worker.onmessage=e=>{const m=e.data||{};
  if(m.type==='ready'){setMetric('#vocab',num(m.vocab));setMetric('#pairs',num(m.pairs));setMetric('#steps',num(m.steps));setMetric('#liveSteps',num(m.steps));setMetric('#loss',m.loss?m.loss.toFixed(3):'—');setMetric('#trainAcc',pct(m.trainAcc||0));setMetric('#valToken',pct(m.valToken||0));setMetric('#valExact',pct(m.valExact||0));syncLive(m);updateTrainButton();}
  else if(m.type==='stats'){currentSteps=m.steps;setMetric('#steps',num(m.steps));setMetric('#liveSteps',num(m.steps));setMetric('#speed',num(Math.round(m.speed)));setMetric('#liveSpeed',num(Math.round(m.speed)));setMetric('#loss',m.loss.toFixed(3));setMetric('#liveLoss',m.loss.toFixed(3));setMetric('#trainAcc',pct(m.trainAcc));setMetric('#liveTrain',pct(m.trainAcc));setMetric('#valToken',pct(m.valToken));setMetric('#liveToken',pct(m.valToken));setMetric('#valExact',pct(m.valExact));setMetric('#liveExact',pct(m.valExact));setMetric('#vocab',num(m.vocab));setMetric('#pairs',num(m.pairs));setMetric('#trainInfo',`${num(m.steps)} exemplos · nível ${1+(m.level||0)}/3 · ${num(Math.round(m.speed))}/s`);$('#progress').style.width=Math.max(m.valToken,m.trainAcc)*100+'%';setMetric('#event',`treino ${pct(m.trainAcc)} · validação token ${pct(m.valToken)} · exato ${pct(m.valExact)}`);syncLive(m);}
  else if(m.type==='snapshot'){try{localStorage.setItem('flytalk-model-v5',JSON.stringify(m.state))}catch{}}
  else if(m.type==='infer'){lastReply=(m.text||'').trim()||'ainda estou aprendendo';lastConfidence=m.confidence||0;lastHidden=m.hidden||[];addMsg('fly',lastReply);$('#confidence').style.width=Math.min(100,lastConfidence*100)+'%';setMetric('#confText',pct(lastConfidence));setMetric('#event','resposta neural gerada palavra por palavra');drawHidden();}
  else if(m.type==='taught'){setMetric('#vocab',num(m.vocab));setMetric('#pairs',num(m.pairs));setMetric('#userPairs',num(userPairs.length));addMsg('sys','Correção adicionada ao treino contínuo.');}
 };
 worker.postMessage({type:'init',pairs:[...BASE_PAIRS,...userPairs],userCount:userPairs.length,valPairs:VAL_PAIRS,state:saved,running,stage:$('#curriculum').value,sliceMs:powerMs()});}
function syncLive(m){for(const id of ['#liveTrain','#liveToken','#liveExact']){const el=$(id);if(!el)continue;const x=parseFloat(el.textContent);el.parentElement.classList.toggle('ok',x>=95);el.parentElement.classList.toggle('warn',x>=70&&x<95)}}
function send(){const text=$('#input').value.trim();if(!text||!worker)return;$('#input').value='';lastPrompt=text;addMsg('user',text);worker.postMessage({type:'infer',id:++inferId,prompt:text})}
$('#send').onclick=send;$('#input').addEventListener('keydown',e=>{if(e.key==='Enter')send()});
$('#train').onclick=()=>{running=!running;worker?.postMessage({type:'run',running});updateTrainButton()};
$('#curriculum').onchange=()=>{worker?.postMessage({type:'stage',stage:$('#curriculum').value});setMetric('#stageInfo',$('#curriculum').value==='auto'?'A complexidade sobe conforme a validação melhora.':'Foco alterado sem reiniciar os pesos.')};
$('#power').onchange=()=>{worker?.postMessage({type:'speed',sliceMs:powerMs()});setMetric('#powerInfo',`janela de treino ${powerMs()} ms · worker em saturação`)};
$('#good').onclick=()=>{if(!lastPrompt||!lastReply)return;worker.postMessage({type:'positive',prompt:lastPrompt,reply:lastReply});addMsg('sys','👍 Resposta reforçada e adicionada ao replay.')};
$('#bad').onclick=()=>{if(!lastPrompt)return;addMsg('sys','👎 Marcada como ruim. Escreva a resposta ideal abaixo para ensinar.');$('#teacher').focus()};
$('#teach').onclick=()=>{const reply=$('#teacher').value.trim();if(!lastPrompt||!reply)return;$('#teacher').value='';userPairs.push([lastPrompt,reply]);userPairs=userPairs.slice(-300);saveUserPairs();worker.postMessage({type:'teach',prompt:lastPrompt,reply})};
$('#save').onclick=()=>worker?.postMessage({type:'snapshot'});
$('#reset').onclick=()=>{if(!confirm('Zerar o modelo treinado? As correções ensinadas por você serão preservadas.'))return;localStorage.removeItem('flytalk-model-v5');startWorker();addMsg('sys','Pesos zerados; suas correções foram preservadas.')};
setMetric('#userPairs',num(userPairs.length));setMetric('#powerInfo',`janela de treino ${powerMs()} ms · worker em saturação`);updateTrainButton();startWorker();
const cv=$('#brain'),cx=cv.getContext('2d');function drawHidden(){cx.fillStyle='#080d14';cx.fillRect(0,0,cv.width,cv.height);if(!lastHidden.length){cx.fillStyle='#93a2b8';cx.font='16px system-ui';cx.fillText('aguardando uma resposta…',14,24);return}const n=lastHidden.length,bw=cv.width/n;for(let i=0;i<n;i++){const v=lastHidden[i],h=Math.abs(v)*(cv.height*.78);cx.fillStyle=v>=0?'rgba(117,230,165,.78)':'rgba(255,127,139,.72)';cx.fillRect(i*bw+1,cv.height*.5-(v>0?h:0),Math.max(2,bw-2),h)}cx.strokeStyle='#36445a';cx.beginPath();cx.moveTo(0,cv.height*.5);cx.lineTo(cv.width,cv.height*.5);cx.stroke();cx.fillStyle='#93a2b8';cx.font='14px system-ui';cx.fillText('estado oculto da última resposta',12,20)}drawHidden();
setInterval(()=>worker?.postMessage({type:'snapshot'}),30000);