const F=384,H=40,MAXV=256,NEG=7,LR=.018;
let vocab=['<eos>','<unk>'],vmap=new Map(vocab.map((x,i)=>[x,i]));
let userCount=0,lastVal=0,autoLevel=0;
let feat=new Float32Array(F*H),tok=new Float32Array(MAXV*H),out=new Float32Array(MAXV*H),bias=new Float32Array(MAXV),bh=new Float32Array(H);
let pairs=[],valPairs=[],running=true,steps=0,lastReport=performance.now(),reportSteps=0,lossEMA=0,stage='auto';
function rnd(a=.08){return (Math.random()*2-1)*a}
for(let i=0;i<feat.length;i++)feat[i]=rnd();for(let i=0;i<tok.length;i++)tok[i]=rnd();for(let i=0;i<out.length;i++)out[i]=rnd();
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/([!?.,])/g,' $1 ').replace(/\s+/g,' ').trim()}
function words(s){return norm(s).split(' ').filter(Boolean)}
function ensure(w){if(vmap.has(w))return vmap.get(w);if(vocab.length>=MAXV)return 1;const id=vocab.length;vocab.push(w);vmap.set(w,id);for(let h=0;h<H;h++){tok[id*H+h]=rnd();out[id*H+h]=rnd()}return id}
function ids(s,add=true){return words(s).map(w=>add?ensure(w):(vmap.get(w)??1))}
function feats(s){const n=norm(s),set=new Set(),ws=n.split(' ').filter(Boolean);for(const w of ws){let h=2166136261;for(let i=0;i<w.length;i++)h=(h^w.charCodeAt(i))*16777619>>>0;set.add(h%F)}for(let i=0;i<n.length-1;i++)set.add(((n.charCodeAt(i)*131+n.charCodeAt(i+1)*17+i*7)>>>0)%F);return [...set].slice(0,28)}
function sig(x){return x>20?1:x<-20?0:1/(1+Math.exp(-x))}
function hidden(fs,p1,p2){const h=new Float32Array(H),scale=1/Math.max(1,fs.length);for(let j=0;j<H;j++){let z=bh[j]+tok[p1*H+j]+.45*tok[p2*H+j];for(const f of fs)z+=feat[f*H+j]*scale;h[j]=Math.tanh(z)}return h}
function score(h,t){let s=bias[t],o=t*H;for(let j=0;j<H;j++)s+=out[o+j]*h[j];return s}
function trainPair(p){const fs=feats(p[0]),ys=ids(p[1],true);ys.push(0);let p1=0,p2=0,total=0;for(const y of ys){const h=hidden(fs,p1,p2),dh=new Float32Array(H),py=sig(score(h,y)),gy=py-1;total+=-Math.log(Math.max(1e-6,py));let oy=y*H;for(let j=0;j<H;j++){dh[j]+=gy*out[oy+j];out[oy+j]-=LR*gy*h[j]}bias[y]-=LR*gy;for(let n=0;n<NEG;n++){let q=2+(Math.random()*Math.max(1,vocab.length-2)|0);if(q===y)q=(q+1)%Math.max(2,vocab.length);const pq=sig(score(h,q)),gq=pq,oq=q*H;total+=-.12*Math.log(Math.max(1e-6,1-pq));for(let j=0;j<H;j++){dh[j]+=.12*gq*out[oq+j];out[oq+j]-=LR*.12*gq*h[j]}bias[q]-=LR*.12*gq}const sc=1/Math.max(1,fs.length);for(let j=0;j<H;j++){const dz=dh[j]*(1-h[j]*h[j]);bh[j]-=LR*.2*dz;tok[p1*H+j]-=LR*.6*dz;tok[p2*H+j]-=LR*.25*dz;for(const f of fs)feat[f*H+j]-=LR*.35*dz*sc}p2=p1;p1=y}return total/ys.length}
function logits(h){const a=new Float32Array(vocab.length);let m=-1e9;for(let i=0;i<a.length;i++){a[i]=score(h,i);if(a[i]>m)m=a[i]}let s=0;for(let i=0;i<a.length;i++){a[i]=Math.exp((a[i]-m)/.85);s+=a[i]}for(let i=0;i<a.length;i++)a[i]/=s||1;return a}
function detok(a){return a.join(' ').replace(/ \?/g,'?').replace(/ !/g,'!').replace(/ ,/g,',').replace(/ \./g,'.')}
function generate(prompt,max=14){const fs=feats(prompt);let p1=0,p2=0,res=[],conf=0,hlast=null;for(let k=0;k<max;k++){const h=hidden(fs,p1,p2),p=logits(h);hlast=Array.from(h);let best=0;for(let i=1;i<p.length;i++)if(p[i]>p[best])best=i;conf+=p[best];if(best===0)break;res.push(vocab[best]||'<unk>');p2=p1;p1=best}return{text:detok(res),confidence:res.length?conf/res.length:0,hidden:hlast||[]}}
function exact(a,b){const aa=words(a),bb=words(b);if(!bb.length)return 0;let hit=0;for(let i=0;i<Math.min(aa.length,bb.length);i++)if(aa[i]===bb[i])hit++;return hit/Math.max(aa.length,bb.length)}
function evalModel(){if(!valPairs.length)return 0;let s=0,n=Math.min(24,valPairs.length);for(let i=0;i<n;i++){const p=valPairs[(Math.random()*valPairs.length)|0];s+=exact(generate(p[0],14).text,p[1])}return s/n}
function augmentPrompt(s){let x=String(s),r=Math.random();if(r<.15)x='ei '+x;else if(r<.28)x='por favor '+x;else if(r<.38)x=x.replace(/você/g,'vc');if(Math.random()<.25)x=x.replace(/[?!.]/g,'');return x}
function choosePair(){if(!pairs.length)return null;if(userCount>0&&Math.random()<.25)return pairs[pairs.length-userCount+(Math.random()*userCount|0)];const base=Math.max(1,pairs.length-userCount);if(stage==='basic')return pairs[Math.random()*Math.max(1,Math.floor(base*.38))|0];if(stage==='qa'){const a=Math.floor(base*.25),b=Math.max(a+1,Math.floor(base*.78));return pairs[a+Math.random()*(b-a)|0]}if(stage==='conversation')return pairs[Math.random()*pairs.length|0];autoLevel=(steps>50000||lastVal>.68)?2:(steps>15000||lastVal>.45)?1:0;const frac=[.38,.72,1][autoLevel],n=Math.max(1,Math.floor(base*frac));return pairs[Math.random()*n|0]}
function snapshot(){return{vocab,feat:Array.from(feat),tok:Array.from(tok.slice(0,vocab.length*H)),out:Array.from(out.slice(0,vocab.length*H)),bias:Array.from(bias.slice(0,vocab.length)),bh:Array.from(bh),steps}}
function restore(s){try{if(!s||!Array.isArray(s.vocab))return;vocab=s.vocab.slice(0,MAXV);vmap=new Map(vocab.map((x,i)=>[x,i]));if(s.feat?.length===feat.length)feat.set(s.feat);if(s.tok)tok.set(s.tok.slice(0,tok.length));if(s.out)out.set(s.out.slice(0,out.length));if(s.bias)bias.set(s.bias.slice(0,bias.length));if(s.bh?.length===bh.length)bh.set(s.bh);steps=s.steps||0}catch{}}
function loop(){if(!running){setTimeout(loop,40);return}const chunk=180;for(let i=0;i<chunk;i++){const p=choosePair();if(!p)break;const l=trainPair([augmentPrompt(p[0]),p[1]]);lossEMA=lossEMA*.99+l*.01;steps++;reportSteps++}const now=performance.now();if(now-lastReport>600){const dt=(now-lastReport)/1000,speed=reportSteps/dt,val=steps%5000<chunk?evalModel():null;if(val!=null)lastVal=val;postMessage({type:'stats',steps,speed,loss:lossEMA,val,vocab:vocab.length,pairs:pairs.length,level:autoLevel});reportSteps=0;lastReport=now;if(steps%10000<chunk)postMessage({type:'snapshot',state:snapshot()})}setTimeout(loop,0)}
onmessage=e=>{const m=e.data||{};if(m.type==='init'){pairs=m.pairs||[];valPairs=m.valPairs||[];userCount=m.userCount||0;restore(m.state);for(const p of [...pairs,...valPairs]){ids(p[0],true);ids(p[1],true)}running=m.running!==false;stage=m.stage||'auto';postMessage({type:'ready',vocab:vocab.length,pairs:pairs.length,steps});loop()}else if(m.type==='run'){running=!!m.running}else if(m.type==='stage'){stage=m.stage||'auto'}else if(m.type==='infer'){postMessage({type:'infer',id:m.id,...generate(m.prompt,16)})}else if(m.type==='teach'){const p=[m.prompt,m.reply];pairs.push(p);userCount++;ids(m.prompt,true);ids(m.reply,true);for(let i=0;i<35;i++)trainPair(p);postMessage({type:'taught',vocab:vocab.length,pairs:pairs.length})}else if(m.type==='positive'){const p=[m.prompt,m.reply];pairs.push(p);for(let i=0;i<8;i++)trainPair(p)}else if(m.type==='snapshot'){postMessage({type:'snapshot',state:snapshot()})}}